# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Release new version"
  lane :release do
  	target_version = options[:version]
	  raise "The version is missed." if target_version.nil?
	  ensure_git_branch                                             # 确认 master 分支
	  # ensure_git_status_clean                                       # 确认没有未提交的文件
	  # scan                                                          # 运行测试

	  sync_build_number_to_git                                      # 将 build 号设为 git commit 数
	  increment_version_number(version_number: target_version)      # 设置版本号

	  version_bump_podspec(path: "FSCycleScrollView.podspec",
	             version_number: target_version)                    # 更新 podspec
	  git_commit_all(message: "Bump version to #{target_version}")  # 提交版本号修改
	  add_git_tag tag: target_version                               # 设置 tag
	  push_to_git_remote                                            # 推送到 git 仓库
	  pod_push                                                      # 提交到 CocoaPods
  end
end
